function [ properties ] = PlotProperties()
%PROPERTIES Returns a struct with various plot properties

properties = struct;

properties.figure = struct;
properties.font = struct;
properties.axes = struct;
properties.line = struct;
properties.legend = struct;

%==========================================================================
properties.figure.dims = struct(...
    'PaperPosition', [0, 0, 8, 5], ...
    'PaperSize', [8, 5] ...
);

%==========================================================================
properties.font.common = struct(...
    'FontName', 'Times New Roman' ...
);

properties.font.title = struct(...
    'FontSize', 15, ...
    'FontWeight', 'bold' ...
);

properties.font.labels = struct(...
    'FontSize', 12, ...
    'FontWeight', 'bold' ...
);

properties.font.axes = struct(...
    'FontSize', 12 ...
);

properties.font.legend = struct(...
    'FontSize', 10 ...
);

%==========================================================================
properties.line.style = struct(...
    'LineWidth', 2, ...
    'Color', Colors() ...
);

%==========================================================================
properties.axes.grid = struct(...
);

%==========================================================================
properties.legend.position = struct(...
    'Units', 'centimeters', ...
    'x', 10, ...
    'y', 10 ...
);

return;
end

