function [ units ] = Units()
%UNITS Returns a struct with units for various properties.

units = struct;

units.field = struct(...
    'TIME', 'Days', ...
    ...
    'FOPT', 'STB', ...
    'FGPT', 'STB', ...
    'FWPT', 'STB', ...
    'FLPT', 'STB', ...
    ...
    'FOPR', 'STB/Day', ...
    'FGPR', 'STB/Day', ...
    'FWPR', 'STB/Day', ...
    'FLPR', 'STB/Day', ...
    ...
    'FPR',  'psi', ...
    'FPRH', 'psi', ...
    ...
    'WBHP', 'psi', ...
    ...
    'WWCT', 'Sm^3', ...
    ...
    'WGPT', 'STB', ...
    'WOPT', 'STB', ...
    'WWPT', 'STB', ...
    'WLPT', 'STB', ...
    ...
    'WLPR', 'STB/Day', ...
    'WOPR', 'STB/Day', ...
    'WWPR', 'STB/Day', ...
    'WGPR', 'STB/Day' ...
);

units.metric = struct(...
    'TIME', 'Days', ...
    ...
    'FOPT', 'Sm3', ...
    'FGPT', 'Sm3', ...
    'FWPT', 'Sm3', ...
    'FLPT', 'Sm3', ...
    ...
    'FOPR', 'Sm3/Day', ...
    'FGPR', 'Sm3/Day', ...
    'FWPR', 'Sm3/Day', ...
    'FLPR', 'Sm3/Day', ...
    ...
    'FPR',  'bar', ...
    'FPRH', 'bar', ...
    ...
    'WBHP', 'bar', ...
    ...
    'WWCT', 'Sm3', ...
    ...
    'WGPT', 'Sm3', ...
    'WOPT', 'Sm3', ...
    'WWPT', 'Sm3', ...
    'WLPT', 'Sm3', ...
    ...
    'WLPR', 'Sm3/Day', ...
    'WOPR', 'Sm3/Day', ...
    'WWPR', 'Sm3/Day', ...
    'WGPR', 'Sm3/Day' ...
);

units.metrictex = struct(...
    'TIME', 'Days', ...
    ...
    'FOPT', '$Sm^{3}$', ...
    'FGPT', '$Sm^{3}$', ...
    'FWPT', '$Sm^{3}$', ...
    'FLPT', '$Sm^{3}$', ...
    ...
    'FOPR', '$Sm^{3}/Day$', ...
    'FGPR', '$Sm^{3}/Day$', ...
    'FWPR', '$Sm^{3}/Day$', ...
    'FLPR', '$Sm^{3}/Day$', ...
    ...
    'FPR',  'bar', ...
    'FPRH', 'bar', ...
    ...
    'WBHP', 'bar', ...
    ...
    'WWCT', '$Sm^{3}$', ...
    ...
    'WGPT', '$Sm^{3}$', ...
    'WOPT', '$Sm^{3}$', ...
    'WWPT', '$Sm^{3}$', ...
    'WLPT', '$Sm^{3}$', ...
    ...
    'WLPR', '$Sm^{3}/Day$', ...
    'WOPR', '$Sm^{3}/Day$', ...
    'WWPR', '$Sm^{3}/Day$', ...
    'WGPR', '$Sm^{3}/Day$' ...
);

end

